In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('student_habits_performance.csv')
df.head(10)

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
5,S1005,24,Male,7.2,1.3,0.0,No,82.9,7.4,Fair,1,Master,Average,4,No,100.0
6,S1006,21,Female,5.6,1.5,1.4,Yes,85.8,6.5,Good,2,Master,Poor,4,No,89.8
7,S1007,21,Female,4.3,1.0,2.0,Yes,77.7,4.6,Fair,0,Bachelor,Average,8,No,72.6
8,S1008,23,Female,4.4,2.2,1.7,No,100.0,7.1,Good,3,Bachelor,Good,1,No,78.9
9,S1009,18,Female,4.8,3.1,1.3,No,95.4,7.5,Good,5,Bachelor,Good,10,Yes,100.0

In [2]:
# Vérification de la taille du dataset
print(f"Le jeu de données a {df.shape[0]} individus et {df.shape[1]} valiables")

Le jeu de données a 1000 individus et 16 valiables

In [3]:
# Vérification du type de chaque variable
df.dtypes

student_id                        object
age                                int64
gender                            object
study_hours_per_day              float64
social_media_hours               float64
netflix_hours                    float64
part_time_job                     object
attendance_percentage            float64
sleep_hours                      float64
diet_quality                      object
exercise_frequency                 int64
parental_education_level          object
internet_quality                  object
mental_health_rating               int64
extracurricular_participation     object
exam_score                       float64
dtype: object

In [4]:
# Statistique descriptive
df.describe()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,84.131700,6.470100,3.042000,5.438000,69.601500
std,2.3081,1.46889,1.172422,1.075118,9.399246,1.226377,2.025423,2.847501,16.888564
min,17.0000,0.00000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.7500,2.60000,1.700000,1.000000,78.000000,5.600000,1.000000,3.000000,58.475000
50%,20.0000,3.50000,2.500000,1.800000,84.400000,6.500000,3.000000,5.000000,70.500000
75%,23.0000,4.50000,3.300000,2.525000,91.025000,7.300000,5.000000,8.000000,81.325000
max,24.0000,8.30000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

In [5]:
# Vérification des valeurs manquantes

df_manque = df.isnull().sum()
df_manque[df_manque > 0]

parental_education_level    91
dtype: int64

In [6]:
# Imputation de la variable parental_education_level par le mode
df['parental_education_level'] = df['parental_education_level'].fillna(df['parental_education_level'].mode()[0])

In [7]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [8]:
# Doublon 
df.duplicated().sum()

np.int64(0)

In [9]:
for col in ['gender', 'part_time_job', 'extracurricular_participation', 
            'diet_quality', 'parental_education_level', 'internet_quality']:
    print(f"{col} : {df[col].unique()}")

gender : ['Female' 'Male' 'Other']
part_time_job : ['No' 'Yes']
extracurricular_participation : ['Yes' 'No']
diet_quality : ['Fair' 'Good' 'Poor']
parental_education_level : ['Master' 'High School' 'Bachelor']
internet_quality : ['Average' 'Poor' 'Good']

In [ ]:
# Encodage des variables catégorielles
from sklearn.preprocessing import OrdinalEncoder

# diet_quality
diet = OrdinalEncoder(categories=[['Poor', 'Fair', 'Good']])
X_train['diet_quality'] = diet.fit_transform(X_train[['diet_quality']])
X_test['diet_quality'] = diet.transform(X_test[['diet_quality']])

# parental_education_level
parent = OrdinalEncoder(categories=[['High School', 'Bachelor', 'Master']])
X_train['parental_education_level'] = parent.fit_transform(X_train[['parental_education_level']])
X_test['parental_education_level'] = parent.transform(X_test[['parental_education_level']])

# internet_quality
internet = OrdinalEncoder(categories=[['Poor', 'Average', 'Good']])
X_train['internet_quality'] = internet.fit_transform(X_train[['internet_quality']])
X_test['internet_quality'] = internet.transform(X_test[['internet_quality']])

In [ ]:
# gender
gender_dummies_train = pd.get_dummies(X_train['gender'], prefix='gender', drop_first=True)
gender_dummies_test = pd.get_dummies(X_test['gender'], prefix='gender', drop_first=True)

# part_time_job
job_dummies_train = pd.get_dummies(X_train['part_time_job'], prefix='job', drop_first=True)
job_dummies_test = pd.get_dummies(X_test['part_time_job'], prefix='job', drop_first=True)

# extracurricular_participation
extra_dummies_train = pd.get_dummies(X_train['extracurricular_participation'], prefix='extra', drop_first=True)
extra_dummies_test = pd.get_dummies(X_test['extracurricular_participation'], prefix='extra', drop_first=True)

In [ ]:
# Suppression des colonnes originales nominales
X_train = X_train.drop(columns=['gender', 'part_time_job', 'extracurricular_participation'])
X_test = X_test.drop(columns=['gender', 'part_time_job', 'extracurricular_participation'])

# Ajout des colonnes encodées
X_train = pd.concat([X_train, gender_dummies_train, job_dummies_train, extra_dummies_train], axis=1)
X_test = pd.concat([X_test, gender_dummies_test, job_dummies_test, extra_dummies_test], axis=1)

print("Shape X_train:", X_train.shape)
print("Shape X_test:", X_test.shape)

Shape X_train: (800, 15)
Shape X_test: (200, 15)

In [ ]:
# Normalisation
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [ ]:
# Conversion en numpy array
X_train_array = X_train_scaler
X_test_array = X_test_scaler
y_train_array = y_train.values
y_test_array = y_test.values

m_train = X_train_array.shape[0]  # nombre de lignes
m_test = X_test_array.shape[0]

# Créer une colonne de 1
ones_train = np.ones((m_train, 1))  # colonne de 1 pour train
ones_test = np.ones((m_test, 1))    # colonne de 1 pour test

# Coller la colonne de 1 à gauche de X
X_train_b = np.hstack([ones_train, X_train_array])
X_test_b = np.hstack([ones_test, X_test_array])


n_features = X_train_b.shape[1]  # nombre de colonnes (features + biais)
w = np.zeros(n_features)

# Implémentation de la régression linéaire
def regression_lineaire(X, w):
    return X @ w

In [ ]:
# Fonction MSE
def mse(y_attendu, y_pred):
    m = len(y_true)
    return (1/m) * np.sum((y_attendu - y_pred)**2)

In [ ]:
# Test
y_pred = regression_lineaire(X_train_b, w)
cout = mse(y_train_array, y_pred)
print("Coût initial :", cout)

Coût initial : 5167.6728875

In [27]:
y_pred = regression_lineaire(X_test_b, w)
cout = mse(y_test_array, y_pred)
print("Coût initial :", cout)

Coût initial : 4975.844300000001